name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build the pages with fastn
        run: |
          eecho "Using '$CI_REPOSITORY_NAME_SLUG/' as the base while building"
          # To deploy the website using GitHub Pages, use the below command
          fastn build --edition=2023 --base=/$CI_REPOSITORY_NAME/
          # To deploy the website using Custom Domain, use the below command and comment
          #out the above command when deploying through GitHub Pages 
          #fastn build --edition=2023 --base=/
      - name: copy CNAME if found
        run: '(test -f CNAME && cp CNAME .build) || echo "CNAME does not exist, skipping step"'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build
